# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/isl-2024',
                'doc_host': 'https://bkowshik.github.io',
                'git_url': 'https://github.com/bkowshik/isl-2024',
                'lib_path': 'isl_2024'},
  'syms': {'isl_2024.core': {'isl_2024.core.foo': ('core.html#foo', 'isl_2024/core.py')}}}
