# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/isl-2024',
                'doc_host': 'https://bkowshik.github.io',
                'git_url': 'https://github.com/bkowshik/isl-2024',
                'lib_path': 'isl_2024'},
  'syms': { 'isl_2024.core': {'isl_2024.core.foo': ('core.html#foo', 'isl_2024/core.py')},
            'isl_2024.scrape_live_stats': { 'isl_2024.scrape_live_stats.fetch_live_stats': ( 'scrape_live_stats.html#fetch_live_stats',
                                                                                             'isl_2024/scrape_live_stats.py')},
            'isl_2024.scrape_matches': {},
            'isl_2024.scrape_wallstream': { 'isl_2024.scrape_wallstream.fetch_wallstream': ( 'scrape_wallstream.html#fetch_wallstream',
                                                                                             'isl_2024/scrape_wallstream.py')},
            'isl_2024.utils': {'isl_2024.utils.get_live_matches': ('utils.html#get_live_matches', 'isl_2024/utils.py')}}}
